"""Agregar columna entregado a tabla venta

Revision ID: 8a6c17660edf
Revises: 
Create Date: 2025-12-06 22:03:09.841005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a6c17660edf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_venta', schema=None) as batch_op:
        batch_op.drop_column('entregado')

    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entregado', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.drop_column('entregado')

    with op.batch_alter_table('item_venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entregado', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
