"""Agregar estatus_pedido a modelo Venta

Revision ID: a6b33325c1c2
Revises: de734caa1c3c
Create Date: 2026-01-16 14:00:00.000000  # (la fecha puede variar)

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6b33325c1c2'
down_revision = 'de734caa1c3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venta', sa.Column('estatus_pedido', sa.String(length=50), server_default='Pedido', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venta', 'estatus_pedido')
    # ### end Alembic commands ###