"""Agregar columna entregado a tabla venta

Revision ID: af38bd3023ca
Revises: 8a6c17660edf
Create Date: 2025-12-06 22:08:24.287925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af38bd3023ca'
down_revision = '8a6c17660edf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_item_venta')
    with op.batch_alter_table('item_venta', schema=None) as batch_op:
        batch_op.drop_column('entregado')

    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entregado', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.drop_column('entregado')

    with op.batch_alter_table('item_venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entregado', sa.INTEGER(), nullable=True))

    op.create_table('_alembic_tmp_item_venta',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('venta_id', sa.INTEGER(), nullable=False),
    sa.Column('producto_id', sa.INTEGER(), nullable=False),
    sa.Column('cantidad', sa.INTEGER(), nullable=False),
    sa.Column('precio', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
